* DimSum

** TODO Permissions

   Behavior (read/write)
   Location (read/write)
   Clone (execute)
   Action (execute)

** TODO Add --public/anonymous flag for insecure installations.
** TODO Allow 'Scopes' to be @dataclasses
** TODO Web tool for 'drawing' connected areas.
** TODO Distance Effects.

   N-Hops aways, etc... This is mostly a tools related thing.

** TODO Weather esp Wind

   Set logical zip code for an area, weather changes to reflect
   that. Wind can blow light items from one area to another.

** TODO Mode: Make Maze.

   Just randomly generates a maze that gets populated with stuff.

** TODO Mode: Animal Crossing

   I think that eventually this will become a thing, but the idea is
   that we can forage for supplies/resources and then use those to
   build other items, using recipes.

   .do recipe Super Cool Thing
   You're holding a recipe.
   .call this NAME

** TODO Mode: Escape Room

   Everybody is thrown into a randomly generated world and has to
   capture a flag or do something? See who can gather the most X in
   whatever time? People can also create their own scenarios, in a
   DnD-esque way and see if their friends can find their way out.
