import plugins.chatting  # noqa
import plugins.creation  # noqa
import plugins.digging  # noqa
import plugins.editing  # noqa
import plugins.fallback  # noqa
import plugins.default  # noqa
import plugins.admin  # noqa
import plugins.looking  # noqa
import plugins.moving  # noqa
import plugins.clothing  # noqa
import plugins.dining  # noqa
import plugins.carrying  # noqa
