import plugins.default.actions  # noqa
import plugins.default.grammar  # noqa
import plugins.default.transformer  # noqa
import plugins.default.admin  # noqa
import plugins.default.looking  # noqa
import plugins.default.moving  # noqa
import plugins.default.clothing  # noqa
import plugins.default.dining  # noqa
import plugins.default.carrying  # noqa
